name: Build, Scan, Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.nginx
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/custom-nginx:latest
      
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/custom-nginx:latest
          format: table
          exit-code: 0

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/custom-nginx:latest
            docker stop nginx_server || true
            docker rm nginx_server || true
            docker run -d --name nginx_server -p 80:80 ${{ secrets.DOCKER_USERNAME }}/custom-nginx:latest
          EOF

      